
deploy:
	gcloud app deploy --project=seizetheball

serve:
	dev_appserver.py app.yaml

browse:
	gcloud app browse --project=seizetheball

create:
	gcloud app create --project=seizetheball --region=europe-west2

viewlogs:
	gcloud app logs tail -s default
