
deploy:
	gcloud app deploy --project=${PROJECT_NAME} --verbosity=info

serve:
	dev_appserver.py app.yaml

browse:
	gcloud app browse --project=${PROJECT_NAME}

create:
	gcloud app create --project=${PROJECT_NAME} --region=europe-west2
